name: Bandit Scan

on: [push, pull_request]

jobs:
  bandit-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bandit Security Scan
        uses: shundor/bandit-action@v1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
